#language: generic
language: node_js
node_js:
  - "10.15.3"

cache: yarn

notifications:
    email: false
  
install: true

matrix:
  fast_finish: true
  include:
    - name: "Home Pipeline"
      env: PACKAGE_LOCATION=packages/home PACKAGE_NAME=home
      if .travis/build-condition.sh $TRAVIS_COMMIT_RANGE packages/home;
    - name: "Cart Pipeline"
      env: PACKAGE_LOCATION=packages/cart PACKAGE_NAME=cart
      if .travis/build-condition.sh $TRAVIS_COMMIT_RANGE packages/cart;

# before_install:
#   - if .travis/build-condition.sh $TRAVIS_COMMIT_RANGE $PACKAGE_LOCATION;
#     then echo "$PACKAGE_LOCATION is being built"
#     else echo "$PACKAGE_LOCATION is NOT being built and deployed"  && travis_terminate 0;
#     fi


script:
  - cd $PACKAGE_LOCATION
  - yarn test
  - yarn build


# script:
#   - if .travis/build-condition.sh $TRAVIS_COMMIT_RANGE $PACKAGE_LOCATION;
#     then echo "$PACKAGE_LOCATION is being built" && cd $PACKAGE_LOCATION && yarn install && yarn test && yarn global add now;
#     else echo "$PACKAGE_LOCATION is NOT being built and deployed"  && travis_terminate 0;
#     fi

deploy:
  - provider: script
    script:  now --token $NOW_TOKEN
    skip_cleanup: true
    app: $PACKAGE_NAME
